backend:
    name: github
    repo: threenine/rea-intelligence

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
    - name: "content"
      label: "Content"
      folder: "content/posts"
      create: true
      slug: "{{slug}}"
      fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "date"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Fullscreen", name: "fullscreen", widget: "boolean" }
          - label: "Tags"
            name: "tags"
            widget: list
            field: { label: "Tag", name: "tag", widget: "string" }
          - {label: "Cover", name: "cover", widget: "image"}
